// ignore_for_file: must_be_immutable

import 'package:flutter/material.dart';
import 'package:scoreboard_app/widgets/king/tekli_king/tekli_king_subclasses/koz_puan.dart';
import '../game_type.dart';

class EighthRow extends StatelessWidget {
  EighthRow({
    required this.oyuncu1puan13,
    required this.oyuncu2puan13,
    required this.oyuncu3puan13,
    required this.oyuncu4puan13,
    required this.oyuncu1puan14,
    required this.oyuncu2puan14,
    required this.oyuncu3puan14,
    required this.oyuncu4puan14,
    required this.oyuncu1puan15,
    required this.oyuncu2puan15,
    required this.oyuncu3puan15,
    required this.oyuncu4puan15,
    required this.oyuncu1puan16,
    required this.oyuncu2puan16,
    required this.oyuncu3puan16,
    required this.oyuncu4puan16,
    required this.oyuncu1puan17,
    required this.oyuncu2puan17,
    required this.oyuncu3puan17,
    required this.oyuncu4puan17,
    required this.oyuncu1puan18,
    required this.oyuncu2puan18,
    required this.oyuncu3puan18,
    required this.oyuncu4puan18,
    required this.oyuncu1puan19,
    required this.oyuncu2puan19,
    required this.oyuncu3puan19,
    required this.oyuncu4puan19,
    required this.oyuncu1puan20,
    required this.oyuncu2puan20,
    required this.oyuncu3puan20,
    required this.oyuncu4puan20,
    super.key,
    required this.onTap,
    required this.activatedCounter,
  });

  int oyuncu1puan13,
      oyuncu2puan13,
      oyuncu3puan13,
      oyuncu4puan13,
      oyuncu1puan14,
      oyuncu2puan14,
      oyuncu3puan14,
      oyuncu4puan14,
      oyuncu1puan15,
      oyuncu2puan15,
      oyuncu3puan15,
      oyuncu4puan15,
      oyuncu1puan16,
      oyuncu2puan16,
      oyuncu3puan16,
      oyuncu4puan16,
      oyuncu1puan17,
      oyuncu2puan17,
      oyuncu3puan17,
      oyuncu4puan17,
      oyuncu1puan18,
      oyuncu2puan18,
      oyuncu3puan18,
      oyuncu4puan18,
      oyuncu1puan19,
      oyuncu2puan19,
      oyuncu3puan19,
      oyuncu4puan19,
      oyuncu1puan20,
      oyuncu2puan20,
      oyuncu3puan20,
      oyuncu4puan20;

  final VoidCallback onTap;
  final int activatedCounter;
  GameType kozlar = GameType(
      gameName: "KOZLAR",
      queue: 7,
      onTap: () {},
      activatedCounter: 0,
      turnRed: 8);

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        kozlar = GameType(
            gameName: "KOZLAR",
            queue: 7,
            onTap: onTap,
            activatedCounter: activatedCounter,
            turnRed: 8),
        KozPuan(
          playerCoordinate: 1,
          gameCoordinate: 7,
          puan1: oyuncu1puan13,
          puan2: oyuncu1puan14,
          puan3: oyuncu1puan15,
          puan4: oyuncu1puan16,
          puan5: oyuncu1puan17,
          puan6: oyuncu1puan18,
          puan7: oyuncu1puan19,
          puan8: oyuncu1puan20,
          widget: kozlar,
        ),
        KozPuan(
          playerCoordinate: 2,
          gameCoordinate: 7,
          puan1: oyuncu2puan13,
          puan2: oyuncu2puan14,
          puan3: oyuncu2puan15,
          puan4: oyuncu2puan16,
          puan5: oyuncu2puan17,
          puan6: oyuncu2puan18,
          puan7: oyuncu2puan19,
          puan8: oyuncu2puan20,
          widget: kozlar,
        ),
        KozPuan(
          playerCoordinate: 3,
          gameCoordinate: 7,
          puan1: oyuncu3puan13,
          puan2: oyuncu3puan14,
          puan3: oyuncu3puan15,
          puan4: oyuncu3puan16,
          puan5: oyuncu3puan17,
          puan6: oyuncu3puan18,
          puan7: oyuncu3puan19,
          puan8: oyuncu3puan20,
          widget: kozlar,
        ),
        KozPuan(
          playerCoordinate: 4,
          gameCoordinate: 7,
          puan1: oyuncu4puan13,
          puan2: oyuncu4puan14,
          puan3: oyuncu4puan15,
          puan4: oyuncu4puan16,
          puan5: oyuncu4puan17,
          puan6: oyuncu4puan18,
          puan7: oyuncu4puan19,
          puan8: oyuncu4puan20,
          widget: kozlar,
        ),
      ],
    );
  }
}
